"""empty message

Revision ID: 39809ce4e753
Revises: af9da098099f
Create Date: 2024-10-29 23:13:45.002940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39809ce4e753'
down_revision = 'af9da098099f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professor')
    # ### end Alembic commands ###
